service: stupid-hack-api

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  stage: dev
  
  environment:
    MONGODB_CLUSTER_URI:
    JWT_SECRET:

functions:
  express:
    handler: handler.handle
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'