service: weight-for-it-api

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  stage: dev
  
  environment:
    MONGODB_CLUSTER_URI: ${env:MONGODB_CLUSTER_URI}

functions:
  express:
    handler: handler.handle
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'

plugins:
   - '@jimdo/serverless-dotenv'
